
name: Continuous Integration

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: python -m pip install --upgrade pip
        
    - name: Run set_up_dev_environment.py
      run: python scripts/set_up_dev_environment.py

    - name: Api code generator
      if: always()
      run: python scripts/lint_tools.py --verify

    - name: Black
      if: always()
      run: python scripts/lint_tools.py --black_check

    - name: Mypy
      if: always()
      run: python scripts/lint_tools.py --mypy

    - name: Pylint
      if: always()
      run: python scripts/lint_tools.py --pylint

    - name: Pycodestyle
      if: always()
      run: python scripts/lint_tools.py --py_code_style

    - name: Test setup
      if: always()
      run: python scripts/test_setup.py.py

    - name: Pdoc3
      if: always()
      run: python scripts/lint_tools.py --pdoc3
    
    - name: Build
      if: always()
      run: python scripts/build_tool.py
